The following unit test runs forever if started as "JUnit Test" from Eclipse. This is essentially the same problem as described in bug 14434. Tested with 3.1.2 and 3.2 I20060223-1656



package test;
import junit.framework.TestCase;
public class MyTest extends TestCase {
  public void test() {
    throw new RuntimeException("Primary problem") {
      public String getLocalizedMessage() {
        throw new RuntimeException("Secondary problem");
      }
    };
  }
}

The following unit test runs forever if started as "JUnit Test" from Eclipse. This is essentially the same problem as described in bug 14434. Tested with 3.1.2 and 3.2 I20060223-1656



package test;
import junit.framework.TestCase;
public class MyTest extends TestCase {
  public void test() {
    throw new RuntimeException("Primary problem") {
      public String getLocalizedMessage() {
        throw new RuntimeException("Secondary problem");
      }
    };
  }
}
Created attachment 37245
proposed fix

This patch guarantes that System.exit(0) will be called. It will also produce better stack trace for the provided test case.
Thanks for the patch, released to HEAD.
.
