Build ID: M20060921-0945

Steps To Reproduce:
1.create a project that has JUnit4 Tests (so that JUnit4TestReference is used in the remote runner)
2.create a JUnit 3 Test
package test;

import junit.framework.TestCase;

public class J3Test extends TestCase {
	public void testA() {
	}

	public void testB() {
	}

	public void testC() {
	}
}

3.select one of the test methods in the Package Explorer and  run as 'Junit Test'

4.the test completes and passed but the below stacktrace is logged in the Error View of PDE runtime:
java.lang.Exception: Unexpected TestElement type for testId '3': null
	at org.eclipse.jdt.internal.junit.model.TestRunSession$TestSessionNotifier.logUnexpectedTest(TestRunSession.java:493)
	at org.eclipse.jdt.internal.junit.model.TestRunSession$TestSessionNotifier.testEnded(TestRunSession.java:397)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient$4.run(RemoteTestRunnerClient.java:484)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:37)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.notifyTestEnded(RemoteTestRunnerClient.java:481)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.access$7(RemoteTestRunnerClient.java:476)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient$DefaultProcessingState.readMessage(RemoteTestRunnerClient.java:90)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.receiveMessage(RemoteTestRunnerClient.java:342)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.access$26(RemoteTestRunnerClient.java:341)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient$ServerConnection.run(RemoteTestRunnerClient.java:267)



More information:
this bug is very similar to 129725, but the stack is different and the test actually passes, it just dumps the err message out to the log

Build ID: M20060921-0945

Steps To Reproduce:
1.create a project that has JUnit4 Tests (so that JUnit4TestReference is used in the remote runner)
2.create a JUnit 3 Test
package test;

import junit.framework.TestCase;

public class J3Test extends TestCase {
	public void testA() {
	}

	public void testB() {
	}

	public void testC() {
	}
}

3.select one of the test methods in the Package Explorer and  run as 'Junit Test'

4.the test completes and passed but the below stacktrace is logged in the Error View of PDE runtime:
java.lang.Exception: Unexpected TestElement type for testId '3': null
	at org.eclipse.jdt.internal.junit.model.TestRunSession$TestSessionNotifier.logUnexpectedTest(TestRunSession.java:493)
	at org.eclipse.jdt.internal.junit.model.TestRunSession$TestSessionNotifier.testEnded(TestRunSession.java:397)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient$4.run(RemoteTestRunnerClient.java:484)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:37)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.notifyTestEnded(RemoteTestRunnerClient.java:481)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.access$7(RemoteTestRunnerClient.java:476)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient$DefaultProcessingState.readMessage(RemoteTestRunnerClient.java:90)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.receiveMessage(RemoteTestRunnerClient.java:342)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.access$26(RemoteTestRunnerClient.java:341)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient$ServerConnection.run(RemoteTestRunnerClient.java:267)



More information:
this bug is very similar to 129725, but the stack is different and the test actually passes, it just dumps the err message out to the log
The stack dump got fixed in 3.3. However, running single JUnit 3 tests in a JUnit 4 project is still not possible. See bug 169222 (it's not supported by junit)

Marking as fixed for the stack trace dump. Using bug 169222 to track the rest.
