RC1

Test Case

import java.io.IOException;

public class Test {
	public void foo() {
		try {
			ex1();
			ex2();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	public void ex1() throws IOException { 
	}
	
	public void ex2 () throws InterruptedException {
	}
}

Observe: the generated catch block is empty.

RC1

Test Case

import java.io.IOException;

public class Test {
	public void foo() {
		try {
			ex1();
			ex2();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	public void ex1() throws IOException { 
	}
	
	public void ex2 () throws InterruptedException {
	}
}

Observe: the generated catch block is empty.
fixed > 20030228
