The class junit.extensions.TestSetup is a decorator to set up additional 
fixture state once before tests are run. I have a TestSuite wrapped into a 
TestSetup for that purpose. The JUnit window in the Java perspective shows 
neither errors (exceptions) nor failures (assertions) that happen in my 
TestSetup.setUp() method. The only thing I get is a comment on the status line:
JUnit test run finished: 1.913 seconds (Errors: 0, Failures: 1)

Just FYI, my class ActivationsTest creates a TestSuite like this:

  public static Test suite() {
    TestSuite suite = new TestSuite();
    suite.addTest( new ActivationsTest( "testAddAccount" ) );
    suite.addTest( new ActivationsTest( "testAddAccountReserveMobile" ) );
    suite.addTest( new ActivationsTest( "testReserveAvailableMobile" ) );
    return new CAMTestSetup( suite, "ActivationsTest" );
  }//suite()

The class junit.extensions.TestSetup is a decorator to set up additional 
fixture state once before tests are run. I have a TestSuite wrapped into a 
TestSetup for that purpose. The JUnit window in the Java perspective shows 
neither errors (exceptions) nor failures (assertions) that happen in my 
TestSetup.setUp() method. The only thing I get is a comment on the status line:
JUnit test run finished: 1.913 seconds (Errors: 0, Failures: 1)

Just FYI, my class ActivationsTest creates a TestSuite like this:

  public static Test suite() {
    TestSuite suite = new TestSuite();
    suite.addTest( new ActivationsTest( "testAddAccount" ) );
    suite.addTest( new ActivationsTest( "testAddAccountReserveMobile" ) );
    suite.addTest( new ActivationsTest( "testReserveAvailableMobile" ) );
    return new CAMTestSetup( suite, "ActivationsTest" );
  }//suite()
Erich, any comments ?
*** Bug 35595 has been marked as a duplicate of this bug. ***
*** Bug 35605 has been marked as a duplicate of this bug. ***
This limitation exists since 2.0. The infrastructure to remove it is now in 
place and we have to fix it immediatly after 2.1
*** Bug 8657 has been marked as a duplicate of this bug. ***
If your TestSetup.setUp() method throws an exception, the test suite will fail, 
but no exception traceback will be shown.

junit.swingui.TestRunner will display the exception, but then you have to 
switch over to Eclipse to find the line where the exception occurred.
fixed
*** Bug 69216 has been marked as a duplicate of this bug. ***
